before_install:
  - psql -U postgres < node/db/schema.sql
  - psql -U postgres < node/db/sample_data.sql

install:
  - cd $TEST_DIR && npm install

script:
  - npm run setup_test

cache:
  directories:
    - "node_modules"
    - "public"
# specify language
language:
    - node_js

node_js:
    - "8.12.0"

matrix:
  include:
  - node: "8.12.0"
    env: TEST_DIR=node
  - node: "8.12.0"
    env: TEST_DIR=react
env:
  global:
      - PGPORT=5432

addons:
  postgresql: "9.4"
