\c project-collab-db;
INSERT INTO users (username, name, bio, password, type) VALUES ('bailey97','Marie Bailey','Sadipscing legere ea elaboraret eu usu ea diam .','wp5CGbFaiDxd', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('freema6','James Freeman','Sadipscing legere ea elaboraret eu usu ea diam .','wp5CGbFaiDxd', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('barnes54','Peter Barnes','Sadipscing legere ea elaboraret eu usu ea diam .','wp5CGbFaiDxd', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('thomas47','Raymond Thomas','Sadipscing legere ea elaboraret eu usu ea diam .','wp5CGbFaiDxd', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('lopez60','Anna Lopez','Sadipscing legere ea elaboraret eu usu ea diam .','wp5CGbFaiDxd', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('wallac8','Robert Wallace','Sadipscing legere ea elaboraret eu usu ea diam .','wp5CGbFaiDxd', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('perry58','Anthony Perry','Sadipscing legere ea elaboraret eu usu ea diam .','wp5CGbFaiDxd', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('robins27','Laura Robinson','Sadipscing legere ea elaboraret eu usu ea diam .','wp5CGbFaiDxd', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('martin56','Paul Martin','Sadipscing legere ea elaboraret eu usu ea diam .','wp5CGbFaiDxd', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('ward65','John Ward','Sadipscing legere ea elaboraret eu usu ea diam .','wp5CGbFaiDxd', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('gonzal82','Michael Gonzalez','Dolor cum ipsum iudico sit elaboraret tamquam .','NvRYj4qj0SXBe', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('lee29','Kathleen Lee','Dolor cum ipsum iudico sit elaboraret tamquam .','NvRYj4qj0SXBe', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('tucker12','Barbara Tucker','Dolor cum ipsum iudico sit elaboraret tamquam .','NvRYj4qj0SXBe', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('reynol18','Barbara Reynolds','Dolor cum ipsum iudico sit elaboraret tamquam .','NvRYj4qj0SXBe', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('sanche44','Michael Sanchez','Dolor cum ipsum iudico sit elaboraret tamquam .','NvRYj4qj0SXBe', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('campbe12','Lisa Campbell','Dolor cum ipsum iudico sit elaboraret tamquam .','NvRYj4qj0SXBe', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('cox53','Dennis Cox','Dolor cum ipsum iudico sit elaboraret tamquam .','NvRYj4qj0SXBe', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('cox83','Virginia Cox','Dolor cum ipsum iudico sit elaboraret tamquam .','NvRYj4qj0SXBe', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('marsha49','Dennis Marshall','Dolor cum ipsum iudico sit elaboraret tamquam .','NvRYj4qj0SXBe', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('sulliv82','Gary Sullivan','Dolor cum ipsum iudico sit elaboraret tamquam .','NvRYj4qj0SXBe', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('steven53','Ronald Stevens','Ullamcorper usu legere offendit ius eos soluta .','aPNUjnATmZ', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('green50','David Green','Ullamcorper usu legere offendit ius eos soluta .','aPNUjnATmZ', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('bell78','David Bell','Ullamcorper usu legere offendit ius eos soluta .','aPNUjnATmZ', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('rogers55','Elizabeth Rogers','Ullamcorper usu legere offendit ius eos soluta .','aPNUjnATmZ', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('marsha33','Angela Marshall','Ullamcorper usu legere offendit ius eos soluta .','aPNUjnATmZ', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('jordan13','Frank Jordan','Ullamcorper usu legere offendit ius eos soluta .','aPNUjnATmZ', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('gibson63','Kevin Gibson','Ullamcorper usu legere offendit ius eos soluta .','aPNUjnATmZ', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('bryant93','Donna Bryant','Ullamcorper usu legere offendit ius eos soluta .','aPNUjnATmZ', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('barnes85','Paul Barnes','Ullamcorper usu legere offendit ius eos soluta .','aPNUjnATmZ', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('west7','Margaret West','Ullamcorper usu legere offendit ius eos soluta .','aPNUjnATmZ', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('jackso68','Martha Jackson','Vel ei cum eos nemore elaboraret cum reprehendunt modus ex .','POXSOgwXei4K', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('reed48','Kenneth Reed','Vel ei cum eos nemore elaboraret cum reprehendunt modus ex .','POXSOgwXei4K', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('gonzal40','Debra Gonzalez','Vel ei cum eos nemore elaboraret cum reprehendunt modus ex .','POXSOgwXei4K', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('stewar48','Thomas Stewart','Vel ei cum eos nemore elaboraret cum reprehendunt modus ex .','POXSOgwXei4K', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('alexan28','Donald Alexander','Vel ei cum eos nemore elaboraret cum reprehendunt modus ex .','POXSOgwXei4K', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('wilson37','Sharon Wilson','Vel ei cum eos nemore elaboraret cum reprehendunt modus ex .','POXSOgwXei4K', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('bailey60','Walter Bailey','Vel ei cum eos nemore elaboraret cum reprehendunt modus ex .','POXSOgwXei4K', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('lewis20','Joshua Lewis','Vel ei cum eos nemore elaboraret cum reprehendunt modus ex .','POXSOgwXei4K', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('taylor52','Brian Taylor','Vel ei cum eos nemore elaboraret cum reprehendunt modus ex .','POXSOgwXei4K', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('bell93','Betty Bell','Vel ei cum eos nemore elaboraret cum reprehendunt modus ex .','POXSOgwXei4K', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('hender52','Ruth Henderson','Eu soluta nemore tamquam sea legere ut enim .','uIkE66iHMj6pkF', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('philli6','Anthony Phillips','Eu soluta nemore tamquam sea legere ut enim .','uIkE66iHMj6pkF', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('adams76','Ronald Adams','Eu soluta nemore tamquam sea legere ut enim .','uIkE66iHMj6pkF', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('barnes30','Gregory Barnes','Eu soluta nemore tamquam sea legere ut enim .','uIkE66iHMj6pkF', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('owens70','Scott Owens','Eu soluta nemore tamquam sea legere ut enim .','uIkE66iHMj6pkF', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('martin91','Kenneth Martinez','Eu soluta nemore tamquam sea legere ut enim .','uIkE66iHMj6pkF', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('davis22','Robert Davis','Eu soluta nemore tamquam sea legere ut enim .','uIkE66iHMj6pkF', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('hicks50','Catherine Hicks','Eu soluta nemore tamquam sea legere ut enim .','uIkE66iHMj6pkF', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('henry65','Raymond Henry','Eu soluta nemore tamquam sea legere ut enim .','uIkE66iHMj6pkF', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('murphy81','Donna Murphy','Eu soluta nemore tamquam sea legere ut enim .','uIkE66iHMj6pkF', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('webb68','Nancy Webb','Ut cum in eu everti lorem diam .','9MTFi4Od4', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('butler65','Anna Butler','Ut cum in eu everti lorem diam .','9MTFi4Od4', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('hender69','Stephanie Henderson','Ut cum in eu everti lorem diam .','9MTFi4Od4', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('wright80','David Wright','Ut cum in eu everti lorem diam .','9MTFi4Od4', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('parker87','Rebecca Parker','Ut cum in eu everti lorem diam .','9MTFi4Od4', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('foster36','Peter Foster','Ut cum in eu everti lorem diam .','9MTFi4Od4', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('torres37','Nancy Torres','Ut cum in eu everti lorem diam .','9MTFi4Od4', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('rivera17','Mary Rivera','Ut cum in eu everti lorem diam .','9MTFi4Od4', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('carter64','Richard Carter','Ut cum in eu everti lorem diam .','9MTFi4Od4', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('robins21','Carolyn Robinson','Ut cum in eu everti lorem diam .','9MTFi4Od4', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('thomps87','Frances Thompson','Usu tamquam cum legere reprehendunt erant elaboraret .','XxgP0ZhWEHiVoR', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('gibson17','Michelle Gibson','Usu tamquam cum legere reprehendunt erant elaboraret .','XxgP0ZhWEHiVoR', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('ross95','Ruth Ross','Usu tamquam cum legere reprehendunt erant elaboraret .','XxgP0ZhWEHiVoR', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('turner59','Ruth Turner','Usu tamquam cum legere reprehendunt erant elaboraret .','XxgP0ZhWEHiVoR', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('webb85','Kevin Webb','Usu tamquam cum legere reprehendunt erant elaboraret .','XxgP0ZhWEHiVoR', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('patter53','Melissa Patterson','Usu tamquam cum legere reprehendunt erant elaboraret .','XxgP0ZhWEHiVoR', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('freema76','Sandra Freeman','Usu tamquam cum legere reprehendunt erant elaboraret .','XxgP0ZhWEHiVoR', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('hunter59','Walter Hunter','Usu tamquam cum legere reprehendunt erant elaboraret .','XxgP0ZhWEHiVoR', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('reed83','Scott Reed','Usu tamquam cum legere reprehendunt erant elaboraret .','XxgP0ZhWEHiVoR', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('baker51','Mark Baker','Usu tamquam cum legere reprehendunt erant elaboraret .','XxgP0ZhWEHiVoR', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('robert34','Carolyn Roberts','Usu qui ea brute usu offendit .','R5Lj5mCBFuq3yQEp', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('james98','Gary James','Usu qui ea brute usu offendit .','R5Lj5mCBFuq3yQEp', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('henry93','Ruth Henry','Usu qui ea brute usu offendit .','R5Lj5mCBFuq3yQEp', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('allen72','Richard Allen','Usu qui ea brute usu offendit .','R5Lj5mCBFuq3yQEp', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('campbe91','Michelle Campbell','Usu qui ea brute usu offendit .','R5Lj5mCBFuq3yQEp', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('gonzal16','Nancy Gonzales','Usu qui ea brute usu offendit .','R5Lj5mCBFuq3yQEp', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('jones98','Elizabeth Jones','Usu qui ea brute usu offendit .','R5Lj5mCBFuq3yQEp', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('robert0','Janet Roberts','Usu qui ea brute usu offendit .','R5Lj5mCBFuq3yQEp', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('wilson60','Joseph Wilson','Usu qui ea brute usu offendit .','R5Lj5mCBFuq3yQEp', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('morgan93','Shirley Morgan','Usu qui ea brute usu offendit .','R5Lj5mCBFuq3yQEp', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('brooks81','Lisa Brooks','Brute everti dolor modus modus modus sea ea eu .','EXLq461D2k', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('bailey68','Matthew Bailey','Brute everti dolor modus modus modus sea ea eu .','EXLq461D2k', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('sulliv30','Scott Sullivan','Brute everti dolor modus modus modus sea ea eu .','EXLq461D2k', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('russel77','Brenda Russell','Brute everti dolor modus modus modus sea ea eu .','EXLq461D2k', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('hill80','David Hill','Brute everti dolor modus modus modus sea ea eu .','EXLq461D2k', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('alexan50','Deborah Alexander','Brute everti dolor modus modus modus sea ea eu .','EXLq461D2k', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('sulliv14','Larry Sullivan','Brute everti dolor modus modus modus sea ea eu .','EXLq461D2k', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('foster37','Marie Foster','Brute everti dolor modus modus modus sea ea eu .','EXLq461D2k', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('turner17','Pamela Turner','Brute everti dolor modus modus modus sea ea eu .','EXLq461D2k', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('ramire13','Dennis Ramirez','Brute everti dolor modus modus modus sea ea eu .','EXLq461D2k', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('price65','Jennifer Price','Offendit periculis eu vel brute dolor eu sea .','8JVymAgz1', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('hernan52','Linda Hernandez','Offendit periculis eu vel brute dolor eu sea .','8JVymAgz1', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('jenkin76','Brenda Jenkins','Offendit periculis eu vel brute dolor eu sea .','8JVymAgz1', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('ramire77','Shirley Ramirez','Offendit periculis eu vel brute dolor eu sea .','8JVymAgz1', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('hall78','Anthony Hall','Offendit periculis eu vel brute dolor eu sea .','8JVymAgz1', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('sander56','Jennifer Sanders','Offendit periculis eu vel brute dolor eu sea .','8JVymAgz1', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('edward30','John Edwards','Offendit periculis eu vel brute dolor eu sea .','8JVymAgz1', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('simmon59','Gary Simmons','Offendit periculis eu vel brute dolor eu sea .','8JVymAgz1', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('morgan2','John Morgan','Offendit periculis eu vel brute dolor eu sea .','8JVymAgz1', 'student');
INSERT INTO users (username, name, bio, password, type) VALUES ('steven70','Jason Stevens','Offendit periculis eu vel brute dolor eu sea .','8JVymAgz1', 'student');

INSERT INTO projects (name, description, project_start_date, status) VALUES ('Google','Iudico ad periculis lorem ipsum . Ipsum vel ullamcorper brute cu sea qui everti enim ex . Periculis autem lorem cum utamur usu ut . Tamquam utamur velit cu offendit ius ius nemore cum amet .','2018-11-24', 'true');
INSERT INTO projects (name, description, project_start_date, status) VALUES ('Project-Collab','Periculis sea nemore autem ut utamur in enim sadipscing . Qui nemore ut usu reprehendunt . In diam autem velit elaboraret velit nemore periculis . Ex ullamcorper sit offendit enim cu lorem ipsum . Amet utamur tamquam sadipscing sea ex modus vel .','2018-11-24', 'true');
INSERT INTO projects (name, description, project_start_date, status) VALUES ('Snapchat','Elaboraret ipsum sea nemore legere periculis . Eu elaboraret eu lorem sit . Legere nemore eos modus cu lorem enim brute nemore nemore . Eos ipsum sea cum vel amet ex . Cu sea iudico sit eu .','2018-11-24', 'true');
INSERT INTO projects (name, description, project_start_date, status) VALUES ('Facebook','Soluta ius diam legere cu sea tamquam sadipscing ius . Ea iudico erant sea diam ex ea . Ei utamur ei ex diam . Ea velit usu enim ex cum . Nemore eu tamquam lorem ipsum .','2018-11-24', 'true');
INSERT INTO projects (name, description, project_start_date, status) VALUES ('DCS','Modus usu utamur eos ad diam . Offendit in elaboraret enim autem usu velit nemore reprehendunt elaboraret . In cum ius eu elaboraret eos . Elaboraret cu enim cum iudico elaboraret .','2018-11-24', 'true');
INSERT INTO projects (name, description, project_start_date, status) VALUES ('ta_feedback','Enim offendit modus eu sea eu offendit . Cu everti nemore enim diam utamur cu .','2018-11-24', 'true');
INSERT INTO projects (name, description, project_start_date, status) VALUES ('PCRS','Sea sadipscing enim vel enim sadipscing enim iudico utamur . Dolor cum brute sea elaboraret sea reprehendunt ei ullamcorper eu . Sea ius erant elaboraret sea vel . Amet ei usu soluta amet ea sea erant ullamcorper ullamcorper . Eu reprehendunt diam ex qui .','2018-11-24', 'true');

INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (60,6,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (26,6,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (8,2,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (34,2,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (2,7,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (55,5,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (87,7,True,'approved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (29,5,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (67,2,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (66,1,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (79,4,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (85,4,True,'approved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (77,1,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (44,3,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (9,1,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (62,5,True,'approved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (93,5,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (39,6,True,'approved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (19,2,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (74,4,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (94,1,True,'approved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (99,6,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (54,4,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (32,1,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (1,3,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (6,5,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (98,1,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (72,4,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (51,2,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (49,7,True,'approved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (20,7,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (82,3,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (52,4,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (37,1,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (18,5,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (61,2,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (53,7,True,'approved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (86,5,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (73,3,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (33,2,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (89,5,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (91,1,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (3,6,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (16,4,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (13,5,True,'approved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (100,3,True,'approved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (38,2,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (75,5,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (88,1,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (97,7,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (59,5,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (76,1,True,'approved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (25,4,True,'approved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (81,6,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (42,7,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (70,7,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (45,7,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (50,1,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (65,6,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (68,4,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (78,3,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (43,6,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (92,5,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (96,6,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (80,4,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (23,5,True,'approved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (46,6,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (95,5,True,'approved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (10,5,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (71,2,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (41,5,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (36,4,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (21,2,True,'approved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (69,3,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (35,4,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (84,4,True,'approved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (47,4,True,'approved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (31,2,True,'approved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (5,7,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (90,7,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (4,7,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (12,2,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (7,5,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (11,7,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (27,6,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (14,4,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (30,1,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (83,1,True,'approved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (24,1,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (22,2,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (57,4,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (48,7,True,'approved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (64,4,True,'approved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (17,5,True,'approved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (56,2,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (58,4,True,'approved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (15,3,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (40,5,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (28,1,False,'unapproved');
INSERT INTO user_associations (user_id, project_id, is_admin, status) VALUES (63,1,False,'unapproved');
